// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwglhnpshyjdmmwnucji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3Z2xobnBzaHlqZG1td251Y2ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTA4NzcsImV4cCI6MjA2NjM2Njg3N30.FI_lCiCJrTdgl-rH59rfte7mh8aAddJTFZ2SGcCSTzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);